on:
  push:
    branches:
      - release/*-rc
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write

name: release-please-rc
env:
  ACTION_NAME: release-please-action
jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: release-please
        uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target-branch: ${{ github.ref_name }}
          release-type: node
          # config-file: releases/release-please-config.json
          # manifest-file: releases/.release-please-manifest.json

      # Checkout
      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
      # Setup node
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release.outputs.release_created }}

      # Install dependencies
      - name: npm install
        run: npm install
        if: ${{ steps.release.outputs.release_created }}

      # Install dependencies
      - name: npm ci
        run: npm ci
        if: ${{ steps.release.outputs.release_created }}

      # Build output
      - name: Build
        run: npm run build
        if: ${{ steps.release.outputs.release_created }}
      # Publish to npm
      - run: |
          git config --global user.email "poechiang@live.cn"
          git config --global user.name "poechiang"
          git add -A
          git commit -m "chore(release please): version ${{ steps.release.outputs.version }} [skip ci]"
          npm version prerelease --preid rc
          git push origin ${{ github.ref_name }} --follow-tags
          npm publish --tag rc
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_SECRET}}
        if: ${{ steps.release.outputs.release_created }}
