#
name: release-npm
on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: "@jeffchi/react-pkg"
          release-pr-title: "chore: release"
          release-pr-body: "chore: release"
          release-to-npm: true
          release-prerelease: false
          release-version: ${{ github.ref }}
          release-pr-labels: "chore: release"
      # Checkout
      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
      # Setup node
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
        if: ${{ steps.release.outputs.release_created }}
      # Setup pnpm
      - uses: pnpm/action-setup@v2
        if: ${{ steps.release.outputs.release_created }}
      # Install dependencies
      - run: pnpm install
        if: ${{ steps.release.outputs.release_created }}
      # Build output

      - name: Build in packages/
        run: |
          for dir in packages/*; do
            if [ -d "$dir" ]; then
              cd "$dir"
              pnpm build
              cd -
            fi
          done
      # Publish to npm
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_SECRET}}
        if: ${{ steps.release.outputs.release_created }}
