#
name: Release to NPM
on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: '@jeffchi/react-pkg'
          bump-patch-for-minor-pre-major: true
          default-branch: main

      # Checkout
      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
      # Setup node
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release.outputs.release_created }}

      # Install dependencies
      - name: npm install
        run: npm install
        if: ${{ steps.release.outputs.release_created }}

      # Install dependencies
      - name: npm ci
        run: npm ci
        if: ${{ steps.release.outputs.release_created }}

      # Build output
      - name: Build
        run: npm run build
        if: ${{ steps.release.outputs.release_created }}
      # Publish to npm
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_SECRET}}
        if: ${{ steps.release.outputs.release_created }}
